### ISSUE TITLE
Please add a config option where you can change the max portal creation distance 

### ISSUE THREAD

**Issue by Yoreni** [Wartori54/ImmersivePortalsSurvivalAdaptation#2]
its annoying that its stuck at 100 with no config option to change it.
i even tryied to download the code remove the limitaton and compile it how ever it wouldnt work.
please add this

**Comment by lolteam4u** [comment]
@Wartori54 I also had this issue there is no way to change, the config option for the distance!

**Comment by Wartori54** [comment]
@Yoreni there's a config for that, it's called "maxPortalCreatorDistance", but if you're the guy that contacted with me in curseforge you are trying it in a server. Currently the server does not load the config due to a bug. I will fix that soon.

**Comment by Wartori54** [comment]
@lolteam4u What distance are you talking about?

**Comment by lolteam4u** [comment]
im with yoreni so which ever limit he was trying

**Comment by Wartori54** [comment]
This should be fixed in 5.0.0
