### ISSUE TITLE
Recent Update

### ISSUE THREAD

**Issue by lolteam4u** [Wartori54/ImmersivePortalsSurvivalAdaptation#3]
**On Recent Update**

On the recent build of the plugin it will not let you join the server and kicks you off with no kick message this however is not the case with Immersive-portals-survival-adaptation-0.4.0.jar where I can join only updating to 0.4.1 breaks it

only Immersive portals survival adaptation 0.4.1+1.17 contains this bug which means you cannot join the server

Log Below is Without 0.4.1 and is with 0.4.0
Password is 000123
https://pastebin.com/LhTYgVU5

This is without 0.4.0 and is on 0.4.1
https://pastebin.com/XVmRKf0b
as you can see I cant join and just get kicked with no error but only when running the newest download

**Comment by Wartori54** [comment]
I can recreate the kick, im trying to fix that.

**Comment by Wartori54** [comment]
Will be fixed in the next release

**Comment by lolteam4u** [comment]
Bug still present in new release cannot join server and get kicked with no reason
