### ISSUE TITLE
Getting Kicked in new release aswell

### ISSUE THREAD

**Issue by lolteam4u** [Wartori54/ImmersivePortalsSurvivalAdaptation#4]
Bug still present in new release cannot join server and get kicked with no reason

_Originally posted by @lolteam4u in https://github.com/Wartori54/ImmersivePortalsSurvivalAdaptation/issues/3#issuecomment-917250086_

**Comment by Wartori54** [comment]
This bug is caused from a library called "nbtcrafting", the current solution is to put nbtcrafting 2.0.19 with this mod, because the latest release has this bug. When i build 5.0.0 i forgot to set that version intead of latest. Sorry for the inconvenience.
Please respond if this fixes the issue.

**Comment by lolteam4u** [comment]
Can i download the same file or do I need to build the mod myself?

**Comment by lolteam4u** [comment]
as there is only the same release from 3 days ago which version number hasn't changed

**Comment by lolteam4u** [comment]
and i dont know how to compile the jar

**Comment by Wartori54** [comment]
You don't need to compile anything, just download nbtcrafting 2.0.19 from [here](https://www.curseforge.com/minecraft/mc-mods/nbt-crafting). And add it to your modpack.
This will replace the nbtcrafting that this mod includes, and fix the disconnects.

**Comment by lolteam4u** [comment]
Fixed you beautiful legand
